### ISSUE TITLE
I want all quiz images to be zero rated

### ISSUE THREAD

**Issue by jack-skerrett-oak** [oaknational/Oak-Web-Application#1666]
https://oaknationalacademy.slack.com/archives/C03HZ76AE3Z/p1685521336447239

**Comment by jimCresswell** [comment]
@mantagen @kpopper Not sure why this wasn't sorted out previously for quiz images... am I right in thinking that in the future those images will be hosted in the DAM, in which case it might make sense to wait until we are using that before doing any additional work?

Also, these requests are technically zero-rated because Netlify is ingesting the images at build time and serving them, but that wasn't by design.
